Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2024
Var
// Seção de Declarações das variáveis 
num:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
num <-6
enquanto (num<=11)faca
 escreva(num)
 num <- num+1
 fimenquanto
escreva(" acabou!")
Fimalgoritmo