Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2024
Var
// Seção de Declarações das variáveis 
I:INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para I<-100 ate 0 passo -10  FACA
ESCREVA(I)
fimpara
escreva(" acabou")
Fimalgoritmo